image: node:10

pipelines:
  branches:
    master:
      - step:
          name: "Build, test and deploy to firebase production"
          deployment: production
          caches:
            - node
          script: 
            - npm install 
            - npm install -g @angular/cli
            - npm install -g firebase-tools
            - npm run build --prod
            - npm run deploy
            - pipe: atlassian/firebase-deploy:0.3.0
              variables:
                  FIREBASE_TOKEN: $FIREBASE_TOKEN

